name: Release build
on:
  push:
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"

      - name: Setup git configs
        run: |
          git checkout master
          git config --global user.name "hackerhgl"
          git config --global user.email "hackerhgl@gmail.com"

      - name: Install puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1
          npm i

      - name: Run puppeteer & commit screenshots
        run: |
          npm run local
          git add .
          git commit -m "Automated jpg & pdf generation"
          git push origin master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Windows release build for github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/assets/hackerhgl-cv.jpg,build/assets/hackerhgl-cv.pdf"
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
